version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
    environment:
      XDEBUG_MODE: coverage
      XDEBUG_CONFIG: client_host=host.docker.internal
    ports:
      - "9003:9003" # Port pour Xdebug
    command: php-fpm

  web:
    image: nginx:alpine
    container_name: symfony_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html  # Mappage du répertoire racine de Symfony
      - ./docker/nginx:/etc/nginx/conf.d  # Mappage des fichiers de config Nginx
    depends_on:
      - php
